apiVersion: v2
name: app-template
description: Generic application chart wrapping the common library chart
type: application
version: 1.0.3
maintainers:
  - name: andrewzn69
dependencies:
  - name: common
    version: "3.2.0"
    repository: oci://ghcr.io/andrewzn69
